"""general_migrate

Revision ID: a49e02c95e80
Revises: 
Create Date: 2025-03-11 19:12:03.596609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49e02c95e80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donate_id'), ['id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)

    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_id'), ['id'], unique=False)

    op.create_table('promocode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('count_use', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocode_id'), ['id'], unique=False)

    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('work', sa.Boolean(), nullable=True),
    sa.Column('pay_switch', sa.Boolean(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['groups.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tgid', sa.BigInteger(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('trial_period', sa.Boolean(), nullable=True),
    sa.Column('special_offer', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('referral_user_tgid', sa.BigInteger(), nullable=True),
    sa.Column('referral_balance', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('lang_tg', sa.String(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('metric', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['groups.name'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric'], ['metric.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tgid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('id_payment', sa.String(), nullable=True),
    sa.Column('month_count', sa.Integer(), nullable=True),
    sa.Column('payment_system', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.create_table('person_promocode_association',
    sa.Column('promocode_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('use', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['promocode_id'], ['promocode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('promocode_id', 'users_id', name='uq_users_promocode')
    )
    op.create_table('vds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('vds_password', sa.String(), nullable=True),
    sa.Column('work', sa.Boolean(), nullable=True),
    sa.Column('max_space', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    with op.batch_alter_table('vds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vds_id'), ['id'], unique=False)

    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_info', sa.String(), nullable=False),
    sa.Column('communication', sa.String(), nullable=True),
    sa.Column('check_payment', sa.Boolean(), nullable=True),
    sa.Column('user_tgid', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_tgid'], ['users.tgid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_id'), ['id'], unique=False)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_vpn', sa.Integer(), nullable=False),
    sa.Column('outline_link', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('connection_method', sa.Boolean(), nullable=True),
    sa.Column('panel', sa.String(), nullable=True),
    sa.Column('inbound_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('actual_space', sa.Integer(), nullable=True),
    sa.Column('work', sa.Boolean(), nullable=True),
    sa.Column('free_server', sa.Boolean(), nullable=True),
    sa.Column('vds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vds'], ['vds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outline_link')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_id'), ['id'], unique=False)

    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tgid', sa.BigInteger(), nullable=True),
    sa.Column('subscription', sa.BigInteger(), nullable=True),
    sa.Column('notion_oneday', sa.Boolean(), nullable=True),
    sa.Column('switch_location', sa.Integer(), nullable=True),
    sa.Column('id_payment', sa.String(), nullable=True),
    sa.Column('trial_period', sa.Boolean(), nullable=True),
    sa.Column('free_key', sa.Boolean(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server'], ['servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_tgid'], ['users.tgid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keys_id'), ['id'], unique=False)

    op.create_table('static_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server'], ['servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('static_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_persons_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_persons_id'))

    op.drop_table('static_persons')
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keys_id'))

    op.drop_table('keys')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_id'))

    op.drop_table('servers')
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_id'))

    op.drop_table('withdrawal_requests')
    with op.batch_alter_table('vds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vds_id'))

    op.drop_table('vds')
    op.drop_table('person_promocode_association')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_id'))

    op.drop_table('location')
    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocode_id'))

    op.drop_table('promocode')
    with op.batch_alter_table('metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_id'))

    op.drop_table('metric')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    with op.batch_alter_table('donate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donate_id'))

    op.drop_table('donate')
    # ### end Alembic commands ###
