"""add_ref_user

Revision ID: ba7a3ffb8d04
Revises: fe0504c85e2b
Create Date: 2025-05-08 17:20:43.565948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7a3ffb8d04'
down_revision: Union[str, None] = 'e7152afbe174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_percent')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
