"""add_table_not_keys

Revision ID: fba5ae3d6764
Revises: ba7a3ffb8d04
Create Date: 2025-08-29 18:26:53.738956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba5ae3d6764'
down_revision: Union[str, None] = 'ba7a3ffb8d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('not_remove_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_key', sa.String(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('not_remove_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_not_remove_key_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('not_remove_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_not_remove_key_id'))

    op.drop_table('not_remove_key')
    # ### end Alembic commands ###
